CREATE TABLE Students
(
	ID INT PRIMARY KEY,
	SerialNumber VARCHAR(50),
	Name VARCHAR(50)
)

CREATE TABLE Problems
(
	ID INT PRIMARY KEY,
	Description VARCHAR(50)
)

CREATE TABLE Assigns
(
	ID INT PRIMARY KEY,
	SID INT FOREIGN KEY REFERENCES Students(ID),
	PID INT FOREIGN KEY REFERENCES Problems(ID)
)

CREATE TABLE Gradings
(
	ID INT PRIMARY KEY,
	AID VARCHAR(50) FOREIGN KEY REFERENCES Assigns(ID),
	Grade INT
)